name: Update DNS

on:
  push:
    branches:
      - main

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse JSON files and update DNS
        run: |
          for FILE in domains/*.json; do
            echo "Processing $FILE..."
            FILENAME=$(basename "$FILE" .json)
            SUBDOMAIN="${FILENAME}.is-always.online"

            A_RECORDS=$(jq -r '.record.A[]?' $FILE)
            AAAA_RECORDS=$(jq -r '.record.AAAA[]?' $FILE)
            CNAME_RECORD=$(jq -r '.record.CNAME?' $FILE)
            URL_RECORD=$(jq -r '.record.URL?' $FILE)
            TXT_RECORDS=$(jq -r '.record.TXT[]?' $FILE)
            PROXIED=$(jq -r '.proxied // false' $FILE)

            if [ -n "$A_RECORDS" ]; then
              for A in $A_RECORDS; do
                if [ "$A" != "null" ]; then
                  echo "Adding A record for $SUBDOMAIN: $A"
                  curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                    --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data '{
                      "type": "A",
                      "name": "'$SUBDOMAIN'",
                      "content": "'$A'",
                      "proxied": '$PROXIED'
                    }'
                fi
              done
            fi

            if [ -n "$AAAA_RECORDS" ]; then
              for AAAA in $AAAA_RECORDS; do
                if [ "$AAAA" != "null" ]; then
                  echo "Adding AAAA record for $SUBDOMAIN: $AAAA"
                  curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                    --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data '{
                      "type": "AAAA",
                      "name": "'$SUBDOMAIN'",
                      "content": "'$AAAA'",
                      "proxied": '$PROXIED'
                    }'
                fi
              done
            fi

            if [ -n "$CNAME_RECORD" ] && [ "$CNAME_RECORD" != "null" ]; then
              echo "Adding CNAME record for $SUBDOMAIN: $CNAME_RECORD"
              curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data '{
                  "type": "CNAME",
                  "name": "'$SUBDOMAIN'",
                  "content": "'$CNAME_RECORD'",
                  "proxied": '$PROXIED'
                }'
            fi

            if [ -n "$TXT_RECORDS" ]; then
              for TXT in $TXT_RECORDS; do
                if [ "$TXT" != "null" ]; then
                  echo "Adding TXT record for $SUBDOMAIN: $TXT"
                  curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                    --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data '{
                      "type": "TXT",
                      "name": "'$SUBDOMAIN'",
                      "content": "'$TXT'",
                      "proxied": '$PROXIED'
                    }'
                fi
              done
            fi
          done
