name: Update DNS

on:
  push:
    branches:
      - main

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse JSON files and update DNS
        run: |
          for FILE in domains/*.json; do
            echo "Processing $FILE..."
            FILENAME=$(basename "$FILE" .json)
            SUBDOMAIN="${FILENAME}.is-always.online"

            A_RECORDS=$(jq -r '.record.A[]?' $FILE)
            AAAA_RECORDS=$(jq -r '.record.AAAA[]?' $FILE)
            CNAME_RECORD=$(jq -r '.record.CNAME?' $FILE)
            URL_RECORD=$(jq -r '.record.URL?' $FILE)
            TXT_RECORDS=$(jq -r '.record.TXT[]?' $FILE)

            if [ -n "$A_RECORDS" ]; then
              for A in $A_RECORDS; do
                echo "Adding A record for $SUBDOMAIN: $A"
                curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                  --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                  --header 'Content-Type: application/json' \
                  --data '{
                    "type": "A",
                    "name": "'$SUBDOMAIN'",
                    "content": "'$A'",
                    "ttl": 120,
                    "proxied": false
                  }'
              done
            fi

            if [ -n "$AAAA_RECORDS" ]; then
              for AAAA in $AAAA_RECORDS; do
                echo "Adding AAAA record for $SUBDOMAIN: $AAAA"
                curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                  --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                  --header 'Content-Type: application/json' \
                  --data '{
                    "type": "AAAA",
                    "name": "'$SUBDOMAIN'",
                    "content": "'$AAAA'",
                    "ttl": 120,
                    "proxied": false
                  }'
              done
            fi

            if [ -n "$CNAME_RECORD" ]; then
              echo "Adding CNAME record for $SUBDOMAIN: $CNAME_RECORD"
              curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data '{
                  "type": "CNAME",
                  "name": "'$SUBDOMAIN'",
                  "content": "'$CNAME_RECORD'",
                  "ttl": 120,
                  "proxied": false
                }'
            fi

            if [ -n "$TXT_RECORDS" ]; then
              for TXT in $TXT_RECORDS; do
                echo "Adding TXT record for $SUBDOMAIN: $TXT"
                curl -X POST 'https://api.cloudflare.com/client/v4/zones/81f8e4f513c5b3c1236812614510e998/dns_records' \
                  --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                  --header 'Content-Type: application/json' \
                  --data '{
                    "type": "TXT",
                    "name": "'$SUBDOMAIN'",
                    "content": "'$TXT'",
                    "ttl": 120
                  }'
              done
            fi
          done
